[profile.default]
src = "contracts"
out = ".build"

libs = ["node_modules", "lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",

]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
local = "http://127.0.0.1:8545"
baseSepolia = "https://sepolia.base.org"

[etherscan]
baseSepolia = { key = "${BASE_SEPOLIA_SCANNER_API_KEY}", url = "${BASE_SEPOLIA_API_URL}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
func_attrs_with_params_multiline = false
quote_style = "double"
wrap_comments = false
